<?php
function xmldb_block_interactivetree_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    /// Add a new column newcol to the mdl_myqtype_options
    if ($oldversion < 2015031200) {
        $blockname='interactivetree';
        
        upgrade_block_savepoint(true, 2015051200, $blockname);
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
    }
    // upgrade_block_savepoint(true, 2014062600, $blockname);

    return true;
}



?>